CONNECTION_URL=jdbc:mysql://localhost:3306/RouteX_Update?useSSL=false&allowPublicKeyRetrieval=true
TRAVELER_USER=traveler
TRAVELER_PASS=traveler
LOGIN_USER=login_User
LOGIN_PASS=login_pass
ADMIN_USER=admin_amministratore_routex
ADMIN_PASS=adminroute